INSERT INTO QUESTION (question_type, question_text, state) VALUES ('Question', 'In Deutschland dürfen Menschen offen etwas gegen die Regierung sagen, weil …', NULL);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (1, 'hier Religionsfreiheit gilt.', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (1, 'die Menschen Steuern zahlen.', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (1, 'die Menschen das Wahlrecht haben.', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (1, 'hier Meinungsfreiheit gilt.', TRUE);
INSERT INTO QUESTION (question_type, question_text, state) VALUES ('Question', 'In Deutschland können Eltern bis zum 14. Lebensjahr ihres Kindes entscheiden, ob es in der Schule am …', NULL);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (2, 'Geschichtsunterricht teilnimmt.', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (2, 'Religionsunterricht teilnimmt.', TRUE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (2, 'Politikunterricht teilnimmt.', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (2, 'Sprachunterricht teilnimmt.', FALSE);
INSERT INTO QUESTION (question_type, question_text, state) VALUES ('Question', 'Deutschland ist ein Rechtsstaat. Was ist damit gemeint?', NULL);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (3, 'Alle Einwohner / Einwohnerinnen und der Staat müssen sich an die Gesetze halten.', TRUE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (3, 'Der Staat muss sich nicht an die Gesetze halten.', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (3, 'Nur Deutsche müssen die Gesetze befolgen.', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (3, 'Die Gerichte machen die Gesetze.', FALSE);
INSERT INTO QUESTION (question_type, question_text, state) VALUES ('Question', 'Welches Recht gehört zu den Grundrechten in Deutschland?', NULL);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (4, 'Waffenbesitz', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (4, 'Faustrecht', FALSE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (4, 'Meinungsfreiheit', TRUE);
INSERT INTO ANSWER (question_id, answer_text, correct) VALUES (4, 'Selbstjustiz', FALSE);