name: Build and Push Docker Images to DOCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.digitalocean.com/quiz-app
      REPOSITORY: quiz-app
      BACKEND_API_BASE_URL: https://quiz-app-backend-6zy4y.ondigitalocean.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_ACCESS_TOKEN }}" | docker login $REGISTRY -u doctl --password-stdin
      
      - name: Build and tag frontend image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_BASE_URL=$BACKEND_API_BASE_URL \
            -t $REGISTRY/$REPOSITORY:frontend ./quiz-app-frontend

#      - name: Build and tag frontend image
#        run: |
#          docker build -t $REGISTRY/$REPOSITORY:frontend ./quiz-app-frontend

      - name: Build and tag backend image
        run: |
          docker build -t $REGISTRY/$REPOSITORY:backend ./quiz-app-backend

      - name: Push frontend image
        run: |
          docker push $REGISTRY/$REPOSITORY:frontend

      - name: Push backend image
        run: |
          docker push $REGISTRY/$REPOSITORY:backend